### ISSUE TITLE
stage4-disk.img don't have X Window System???

### ISSUE THREAD

**Issue by yosukezith** [rwmjones/fedora-riscv-stage4#2]
I want to install GUI on fedora28 on riscv-qemu.
So I commanded yum groupinstall "X Window System" 
But fedora says "X Window System" does not exist.
X Window System don't exist on RISC-V Fedora?

And When I command "startx" in fedora, error was back....

**Comment by rwmjones** [comment]
Oh hi, I guess we never really check these issues.  However certainly X should exist, but you will probably need to pull packages from the new Koji build system that we are setting up.  It's not very well integrated at the moment, but that's coming soon.

http://fedora-riscv.tranquillity.se/koji/

**Comment by rwmjones** [comment]
By the way probably better to ask questions on the `#fedora-riscv` IRC channel.
